# -*- coding: utf-8 -*-
"""Bangla number to English number convesion

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z4zWV3nCQFcLkUx5TwPk49dWNXPbLAqO
"""

# একটি ফাংশন যেটি বাংলা নাম্বারকে ইংলিশে পরিবর্তন করে , বাংলা নাম্বারের স্ট্রীং হিসেবে ইনপুট দিলে 
 # A function that takes Bangla numerical value in form to string and return English numerical value 

def bangla_to_eng_num_covert(bangla_number): 

    # বাংলা নাম্বার গুলোকে স্টোর করার জন্য একটা লিস্টে সংখ্যা গুলো নিয়ে নিলাম
    # Defining a list to store the Bangla numerical numbers each

    বাংলা_নাম্বারের_সারণি = ["০","১","২","৩","৪","৫","৬","৭","৮","৯"]

    # একটা খালি স্ট্রীং নিয়ে নিলাম যেন পরে পরিবর্তীত ভাল্যুটা রাখতে পারি
    # Taking a empty string to store the converted value

    converted_number = ""

    # পুরো নাম্বারের প্রতিটা সংখাকে চেক করার জন্য একটা লুপ নিলাম 
    # Taking a loop for checking each number in Bangla

    for i in bangla_number:

      # আমি এমন ভাবে বাংলা নাম্বারের সারনীটা সাজিয়েছি তাই তার ইন্ডেক্স টাকে নিলেই ইংলিশ সংখাতে নিতে পারবো এবং এর পর খালি স্ট্রীংটার সাথে জোড়া লাগাচ্ছি 
      # I defined the numbers in such a way that by taking just index values of the Bangla number matches the english values

      try: 
        converted_number += str(  বাংলা_নাম্বারের_সারণি.index(i) )

      # যদি বাংলা নাম্বার ছাড়া অন্য কিছু ইনপুট দেওয়া হয়
      # If input is not a Bangla number
      except ValueError:
        print("The input string is not a Bangla number / ইনপুটকৃত স্ট্রীংটি বাংলা সংখ্যা না ")
        
        # কোড রান করা বন্ধ করে দিবে
        # Stop execution
        return None

    # ইংলিশে পরিবর্তিত নাম্বারটিকে ফেরত পাঠাচ্ছি
    # Returning the converted English number 
    return converted_number

# Bangla Numebr
# বাংলা নাম্বারটি 
bangla_number = input("Enter a Bangla number/ একটি বাংলা নাম্বার দিন : ")

# Testing the function
# ফাংশনটি কাজ করছে কিনা দেখি

print("English Number/ ইংলিশ নাম্বারটি :", bangla_to_eng_num_covert(bangla_number))