# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gTeCoDO71ItttWnZbMfgJAkuEzlOZEEr
"""

def bangla_to_eng_num_covert(bangla_number): 

    # বাংলা নাম্বার গুলোকে স্টোর করার জন্য একটা ডিকশনারিতে সংখ্যা গুলো নিয়ে নিলাম
    # Defining a dictionary to store the Bangla numerical numbers each

    বাংলা_নাম্বারের_সারণি = {    "০" : "0",
                             "১" : "1",
                             "২" : "2",
                             "৩" : "3",
                             "৪" : "4",
                             "৫": "5",
                             "৬": "6",
                             "৭": "7",
                             "৮": "8",
                             "৯": "9"}

    # একটা খালি স্ট্রীং নিয়ে নিলাম যেন পরে পরিবর্তীত ভাল্যুটা রাখতে পারি
    # Taking a empty string to store the converted value

    converted_number = ""

    # পুরো নাম্বারের প্রতিটা সংখাকে চেক করার জন্য একটা লুপ নিলাম 
    # Taking a loop for checking each number in Bangla

    for i in bangla_number:

      # আমি এমন ভাবে বাংলা নাম্বারের সারনীটা সাজিয়েছি তাই তার ভ্যালু টাকে নিলেই ইংলিশ সংখাতে নিতে পারবো এবং এর পর খালি স্ট্রীংটার সাথে জোড়া লাগাচ্ছি 
      # I defined the numbers in such a way that by taking just values of the Bangla number matches the english values

      try: 
        converted_number +=   বাংলা_নাম্বারের_সারণি[i] 

      # যদি বাংলা নাম্বার ছাড়া অন্য কিছু ইনপুট দেওয়া হয়
      # If input is not a Bangla number
      except KeyError :
        print("The input string is not a Bangla number / ইনপুটকৃত স্ট্রীংটি বাংলা সংখ্যা না ")
        
        # কোড রান করা বন্ধ করে দিবে
        # Stop execution
        return None

    # ইংলিশে পরিবর্তিত নাম্বারটিকে ফেরত পাঠাচ্ছি
    # Returning the converted English number 
    return converted_number

# Bangla Numebr
# বাংলা নাম্বারটি 
bangla_number = input("Enter a Bangla number/ একটি বাংলা নাম্বার দিন : ")

# Testing the function
# ফাংশনটি কাজ করছে কিনা দেখি

print("English Number/ ইংলিশ নাম্বারটি :", bangla_to_eng_num_covert(bangla_number))