# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zR1Uj7sE9gdjUXU1vIPXMSbNddgUEBrg
"""

class Bangla_num_operations:
 
  def bangla_to_eng_num_covert(self,bangla_number):
    
    # বাংলা নাম্বার গুলোকে স্টোর করার জন্য একটা ডিকশনারিতে সংখ্যা গুলো নিয়ে নিলাম
    # Defining a dictionary to store the Bangla numerical numbers each

    বাংলা_নাম্বারের_সারণি = {    "০" : "0",
                            "১" : "1",
                            "২" : "2",
                            "৩" : "3",
                            "৪" : "4",
                            "৫": "5",
                            "৬": "6",
                            "৭": "7",
                            "৮": "8",
                            "৯": "9",
                             "." :"."}

    # একটা খালি list নিয়ে নিলাম যেন পরে পরিবর্তীত ভাল্যুটা রাখতে পারি
    # Taking a empty list to store the converted value

    converted_number = []

    # পুরো নাম্বারের প্রতিটা সংখাকে চেক করার জন্য একটা লুপ নিলাম 
    # Taking a loop for checking each number in Bangla

    for i in bangla_number: # O(n)

      # খালি লিস্টটিতে পরিবর্তিত সংখ্যা গুলো জোড়া লাগাচ্ছি 
      # Appending the English values into empty list

      try: 
        converted_number.append(বাংলা_নাম্বারের_সারণি[i] ) # O(1)

      # যদি বাংলা নাম্বার ছাড়া অন্য কিছু ইনপুট দেওয়া হয়
      # If input is not a Bangla number
      except KeyError :
        print("The input string is not a Bangla number / ইনপুটকৃত স্ট্রীংটি বাংলা সংখ্যা না ")
        
        # কোড রান করা বন্ধ করে দিবে
        # Stop execution
        return None

    # ইংলিশে পরিবর্তিত নাম্বারটিকে ফেরত পাঠাচ্ছি
    # Returning the converted English number 
    return "".join(converted_number) # O(n)
    

p1 = Bangla_num_operations()

x=p1.bangla_to_eng_num_covert("7894561.178")
print(x)